#!/bin/sh


dir="$( cd "$( dirname "$0" )" && pwd )"
cd "$dir"

echo $dir

if [ ! -d "$dir/sbt/repository" ] ; then 
    cd "$dir/sbt" && unzip "$dir/sbt/repository.zip"
fi

cd "$dir"

if [ ! -d "$dir/sbt/sbt" ] ; then
    cd "$dir/sbt" && unzip "$dir/sbt/sbt.zip"
fi

cd "$dir"

sbt="$dir/sbt/sbt-launch.jar"



# tweak this line according to your needs
java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 $SBT_PROPS -Dsbt.ivy.home="$dir/sbt/repository" -Dsbt.boot.directory="$dir/sbt/boot" -Dsbt.boot.properties="$dir/sbt/sbt.boot.properties" -Xmx512M -jar -Dfile.encoding=UTF8 -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m "$sbt" "$@"

